"use client";
import { useState } from "react";

const faqs = [
  {
    q: "How does it work?",
    a: "Translync captures the speaker's audio through a browser microphone, transcribes it using AI speech recognition, translates the text into the target languages, and delivers the result as both text and synthesized audio to each listener's device -- all in under 2 seconds.",
  },
  {
    q: "What languages are supported?",
    a: "We support 70+ languages including Spanish, French, German, Arabic, Mandarin, Japanese, Korean, Russian, Portuguese, Hindi, Swahili, and many more. If you need a specific language not listed, contact us -- we are constantly expanding coverage.",
  },
  {
    q: "Do attendees need to install an app?",
    a: "No. Attendees simply scan a QR code or tap a link. The translation opens directly in their phone's browser. No app store, no downloads, no accounts required.",
  },
  {
    q: "How accurate is the translation?",
    a: "For standard speech in common languages, accuracy is 90-95%. For specialized terminology (religious, medical, legal), you can use built-in domain glossaries or upload your own custom glossary to improve results further.",
  },
  {
    q: "What about audio quality?",
    a: "Translation audio is generated by AI text-to-speech, which produces natural-sounding voices. For best results, use a decent microphone in a reasonably quiet environment. The system handles background noise well, but a clear audio source always helps.",
  },
  {
    q: "Is there a free trial?",
    a: "Yes. Every account starts with 30 free minutes of translation per month -- no credit card required. This is enough to run a full test with your actual content before committing to a paid plan.",
  },
];

export default function FAQ() {
  const [open, setOpen] = useState<number | null>(null);

  return (
    <section id="faq" className="py-24 bg-gray-50">
      <div className="max-w-3xl mx-auto px-6">
        <div className="text-center mb-16">
          <h2 className="text-3xl sm:text-4xl font-bold text-gray-900 mb-4">
            Frequently asked questions
          </h2>
          <p className="text-lg text-gray-600">
            Everything you need to know before getting started.
          </p>
        </div>

        <div className="space-y-3">
          {faqs.map((faq, i) => (
            <div
              key={i}
              className="bg-white rounded-xl border border-gray-200 overflow-hidden"
            >
              <button
                className="w-full text-left px-6 py-5 flex justify-between items-center font-semibold text-gray-900 hover:bg-gray-50 transition-colors"
                onClick={() => setOpen(open === i ? null : i)}
                aria-expanded={open === i}
              >
                <span>{faq.q}</span>
                <svg
                  className={`w-5 h-5 text-gray-400 shrink-0 ml-4 transition-transform duration-200 ${
                    open === i ? "rotate-180" : ""
                  }`}
                  fill="none"
                  viewBox="0 0 24 24"
                  strokeWidth={2}
                  stroke="currentColor"
                >
                  <path
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    d="m19.5 8.25-7.5 7.5-7.5-7.5"
                  />
                </svg>
              </button>
              {open === i && (
                <div className="px-6 pb-5 text-gray-600 leading-relaxed text-sm border-t border-gray-100 pt-4">
                  {faq.a}
                </div>
              )}
            </div>
          ))}
        </div>
      </div>
    </section>
  );
}
