export default function JsonLd() {
  const schema = {
    "@context": "https://schema.org",
    "@graph": [
      {
        "@type": "SoftwareApplication",
        "@id": "https://translync.app/#software",
        name: "Translync",
        applicationCategory: "BusinessApplication",
        operatingSystem: "Web",
        description:
          "Real-time AI translation for events, churches, NGOs, and conferences. 70+ languages, no hardware required.",
        url: "https://translync.app",
        offers: {
          "@type": "Offer",
          price: "3.00",
          priceCurrency: "USD",
          description: "Per hour per language. Pay as you go.",
        },
        featureList: [
          "Real-time speech translation",
          "70+ languages supported",
          "No hardware required",
          "QR code audience access",
          "Live organizer dashboard",
          "Session recording included",
        ],
        aggregateRating: {
          "@type": "AggregateRating",
          ratingValue: "4.9",
          reviewCount: "47",
        },
      },
      {
        "@type": "Organization",
        "@id": "https://translync.app/#org",
        name: "Translync",
        url: "https://translync.app",
        logo: "https://translync.app/icon.svg",
        description: "AI-powered real-time translation for events and organizations",
        contactPoint: {
          "@type": "ContactPoint",
          email: "hello@translync.app",
          contactType: "customer support",
        },
      },
      {
        "@type": "WebSite",
        "@id": "https://translync.app/#website",
        url: "https://translync.app",
        name: "Translync",
        publisher: { "@id": "https://translync.app/#org" },
      },
      {
        "@type": "FAQPage",
        "@id": "https://translync.app/#faq",
        mainEntity: [
          {
            "@type": "Question",
            name: "How does it work?",
            acceptedAnswer: {
              "@type": "Answer",
              text: "Translync captures the speaker's audio through a browser microphone, transcribes it using AI speech recognition, translates the text into the target languages, and delivers the result as both text and synthesized audio to each listener's device — all in under 2 seconds.",
            },
          },
          {
            "@type": "Question",
            name: "What languages are supported?",
            acceptedAnswer: {
              "@type": "Answer",
              text: "We support 70+ languages including Spanish, French, German, Arabic, Mandarin, Japanese, Korean, Russian, Portuguese, Hindi, Swahili, and many more.",
            },
          },
          {
            "@type": "Question",
            name: "Do attendees need to install an app?",
            acceptedAnswer: {
              "@type": "Answer",
              text: "No. Attendees simply scan a QR code or tap a link. The translation opens directly in their phone's browser. No app store, no downloads, no accounts required.",
            },
          },
          {
            "@type": "Question",
            name: "How accurate is the translation?",
            acceptedAnswer: {
              "@type": "Answer",
              text: "For standard speech in common languages, accuracy is 90-95%. For specialized terminology (religious, medical, legal), you can use built-in domain glossaries or upload your own custom glossary to improve results further.",
            },
          },
          {
            "@type": "Question",
            name: "What about audio quality?",
            acceptedAnswer: {
              "@type": "Answer",
              text: "Translation audio is generated by AI text-to-speech, which produces natural-sounding voices. For best results, use a decent microphone in a reasonably quiet environment.",
            },
          },
          {
            "@type": "Question",
            name: "Is there a free trial?",
            acceptedAnswer: {
              "@type": "Answer",
              text: "Yes. Every account starts with 30 free minutes of translation per month — no credit card required. This is enough to run a full test with your actual content before committing to a paid plan.",
            },
          },
        ],
      },
    ],
  };

  return (
    <script
      type="application/ld+json"
      dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }}
    />
  );
}
