import type { Metadata } from "next";
import Breadcrumbs from "@/components/Breadcrumbs";
import Navbar from "@/components/Navbar";

export const metadata: Metadata = {
  title: "Terms of Service — Translync",
  description: "Translync terms of service. Rules and conditions for using our real-time translation platform.",
  alternates: { canonical: "https://translync.app/terms" },
};

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-gray-50">
      <Navbar />

      <main className="max-w-3xl mx-auto px-6 py-12">
        <Breadcrumbs items={[{ label: "Home", href: "/" }, { label: "Terms of Service" }]} />
        <h1 className="text-3xl font-bold text-gray-900 mb-8">Terms of Service</h1>
        <p className="text-sm text-gray-400 mb-8">Last updated: March 2026</p>

        <div className="prose prose-gray max-w-none space-y-6 text-gray-700 text-sm leading-relaxed">
          <section>
            <h2 className="text-lg font-bold text-gray-900 mt-8 mb-3">1. Service Description</h2>
            <p>Translync provides real-time AI-powered translation for live events. The service transcribes spoken audio, translates it into selected target languages, and delivers the translation as text and synthesized audio to attendees via web browser.</p>
          </section>

          <section>
            <h2 className="text-lg font-bold text-gray-900 mt-8 mb-3">2. Account & Access</h2>
            <ul className="list-disc list-inside space-y-1 ml-4">
              <li>You must provide a valid email address to create an account.</li>
              <li>You are responsible for all activity under your account.</li>
              <li>Attendees can join sessions without an account by scanning a QR code.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-lg font-bold text-gray-900 mt-8 mb-3">3. Free Tier & Pricing</h2>
            <ul className="list-disc list-inside space-y-1 ml-4">
              <li>Every account receives 30 free minutes of translation per month.</li>
              <li>Beyond the free tier, translation costs $3 per hour per target language.</li>
              <li>Pricing may change with 30 days notice.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-lg font-bold text-gray-900 mt-8 mb-3">4. Acceptable Use</h2>
            <p>You agree not to:</p>
            <ul className="list-disc list-inside space-y-1 ml-4">
              <li>Use the service for unlawful purposes.</li>
              <li>Attempt to reverse-engineer the translation engine.</li>
              <li>Overload the service with automated or abusive requests.</li>
              <li>Record or redistribute translated content without the speaker's consent.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-lg font-bold text-gray-900 mt-8 mb-3">5. Translation Quality</h2>
            <p>Translations are generated by AI and may contain errors. Translync does not guarantee 100% accuracy. For legal, medical, or safety-critical content, professional human translation should be used alongside or instead of this service.</p>
          </section>

          <section>
            <h2 className="text-lg font-bold text-gray-900 mt-8 mb-3">6. Data & Sessions</h2>
            <ul className="list-disc list-inside space-y-1 ml-4">
              <li>Session data (audio, transcripts, translations) expires automatically after 24 hours.</li>
              <li>We do not permanently store audio recordings unless you explicitly opt in to a future recording feature.</li>
              <li>See our <a href="/privacy" className="text-blue-600 hover:underline">Privacy Policy</a> for details on data handling.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-lg font-bold text-gray-900 mt-8 mb-3">7. Service Availability</h2>
            <p>We aim for high availability but do not guarantee uninterrupted service. Real-time translation depends on internet connectivity, third-party API availability, and audio quality. We are not liable for interruptions caused by factors outside our control.</p>
          </section>

          <section>
            <h2 className="text-lg font-bold text-gray-900 mt-8 mb-3">8. Limitation of Liability</h2>
            <p>Translync is provided &ldquo;as is.&rdquo; To the maximum extent permitted by law, we are not liable for any indirect, incidental, or consequential damages arising from use of the service, including but not limited to translation errors, service outages, or data loss.</p>
          </section>

          <section>
            <h2 className="text-lg font-bold text-gray-900 mt-8 mb-3">9. Termination</h2>
            <p>You may delete your account at any time. We may suspend or terminate accounts that violate these terms. Upon termination, all session data will be deleted.</p>
          </section>

          <section>
            <h2 className="text-lg font-bold text-gray-900 mt-8 mb-3">10. Contact</h2>
            <p>For questions about these terms, contact <a href="mailto:hello@translync.app" className="text-blue-600 hover:underline">hello@translync.app</a>.</p>
          </section>
        </div>
      </main>

      <footer className="border-t border-gray-200 py-8 text-center text-sm text-gray-400">
        <a href="/" className="hover:text-gray-600">Translync</a> · <a href="/privacy" className="hover:text-gray-600">Privacy</a>
      </footer>
    </div>
  );
}
